#!/bin/bash
FILE=""
PACKAGE=""
SDK="$HOME/Android/Sdk/build-tools/36.1.0"
OPTSTRING="f:p:s:h"
while getopts ${OPTSTRING} opt; do
	case ${opt} in
		f)
			FILE=${OPTARG}
			;;
		p)
			PACKAGE=${OPTARG}
			;;

		h)
			echo "Run this from the location you decompiled in"
			printf "f : FILE\np : PACKAGE to uninstall\ns : Android SDK path\n"
			echo "See file for more details"
			exit
			;;
	esac
done

if [[ -z $FILE ]]; then
	echo "Specify a filename"
	exit
fi

#uninstall the package so we can clean install
#If we do not do this, our app will not install over the current
if [[ -n $PACKAGE ]]; then
	sudo waydroid shell pm uninstall $PACKAGE
else
	echo "CAREFUL! We didn't uninstall the old version"
fi

echo $FILE
apktool b --use-aapt -d $FILE

TARGET="$FILE/dist/$FILE.apk"
SIGN_TARGET="$TARGET""_out.apk"

ALIGN="$SDK/zipalign -p 4 $TARGET $SIGN_TARGET"
rm $SIGN_TARGET
echo $ALIGN
eval $ALIGN

SIGN="$SDK/apksigner sign -ks ~/modding/my-release-key.keystore --ks-pass pass:Mypass $SIGN_TARGET"
#jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/modding/my-release-key.keystore $PWD/$FILE/dist/$FILE.apk alias_name -storepass Mypass
echo $SIGN
eval $SIGN

waydroid app install $PWD/$SIGN_TARGET
